### ISSUE TITLE
Chapter 4: the cube is off-center

### ISSUE THREAD

**Issue by blue-apparition** [ButchDean/interactive_computer_graphics#2]
Hello. I'm learning OpenGL. In Chapter 4, in all 3 examples, I see the cube at the right top corner. Not sure if it's centered there, but I certainly don't see all the edges, so I can't see the "perspectiveness", if it works or not (screenshot: https://c.radikal.ru/c00/1811/dc/31adcf019309.png). Examples in Chapter 3 work fine, cube is centered. I have AMD HD7750 (GCNv1), on Debian 9 64 bits with open driver (radeon). Any ideas? Thanks.

**Comment by ButchDean** [comment]
I haven't run these examples in a while so couldn't tell you if this is expected, although I doubt it. Looking at the code there are keys you can press to adjust the camera view that will allow you to see the cube, so I would give that a try.

**Comment by ButchDean** [comment]
I guess this is resolved.
