### ISSUE TITLE
open gl on windows 

### ISSUE THREAD

**Issue by mxmzry** [ButchDean/interactive_computer_graphics#3]
hi thanks for sharing is it possible to change the cmakelists so it downloads the apprpriate opengl libraries and make conditions working with clion will be very helpful thanls

**Comment by ButchDean** [comment]
Hi @slowpoison88 

Sorry I missed this. This is solely for building on Linux and assumes you have the appropriate libraries installed to build successfully on your distro. Also, going by the title of your issue, there are no plans to support Windows from this repo. There are the Windows versions [https://www.cs.unm.edu/~angel/BOOK/INTERACTIVE_COMPUTER_GRAPHICS/SIXTH_EDITION/CODE/](here) which I have not tested.

Given that I also work with Mac I'm thinking of getting these samples going on that platform eventually but not anytime soon.

Enjoy OpenGL! :)

**Comment by mxmzry** [comment]
Thanks
